version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "robocon2025"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "robocon2024"
    schedule:
      interval: "daily"
